b = '<div class="ticker"><div class="ticker-label"><span class="iconify" data-icon="lucide:zap"></span> TRENDING</div><div class="ticker-track" id="tk"></div></div>'
b += '<header class="header"><a href="#" class="logo">Trend<b>Scope</b></a></header>'
b += '<div class="main"><aside class="sidebar-l"><div class="sb-title">Domains</div><div id="sb"></div></aside>'
b += '<main class="content" id="ct"><div class="controls">'
b += '<div class="ctrl-grp"><label class="ctrl-label">Domain</label><select class="ctrl-in" id="dm"></select></div>'
b += '<div class="ctrl-grp grow"><label class="ctrl-label">Sub-Topic</label><input class="ctrl-in" id="st" placeholder="e.g., LLMs, Fintech..."></div>'
b += '<div class="ctrl-grp"><label class="ctrl-label">Range</label><div class="chips"><button class="chip" data-d="1" onclick="setD(1)">1D</button><button class="chip active" data-d="7" onclick="setD(7)">7D</button><button class="chip" data-d="30" onclick="setD(30)">30D</button></div></div>'
b += '<button class="btn-gen" onclick="go()"><span class="iconify" data-icon="lucide:sparkles"></span> Generate</button>'
b += '<button class="btn-dl" onclick="dl()"><span class="iconify" data-icon="lucide:download"></span> PDF</button></div>'
b += '<div id="nc"><div class="empty"><div class="ic"><span class="iconify" data-icon="lucide:newspaper"></span></div><h3>Select a Domain</h3><p>Choose a domain from the sidebar to view news.</p></div></div></main>'
b += '<aside class="sidebar-r"><div class="rs-title"><span class="live-dot"></span> Live Activity</div><div class="log" id="lg"></div></aside></div>'
b += '<script>\nvar DM=' + chr(123) + chr(34) + 'Artificial Intelligence (AI)' + chr(34) + ':' + chr(123) + chr(34) + 'Machine Learning' + chr(34) + ':' + chr(34) + 'machine learning' + chr(34) + ',' + chr(34) + 'LLMs' + chr(34) + ':' + chr(34) + 'LLM OR GPT' + chr(34) + ',' + chr(34) + 'Robotics' + chr(34) + ':' + chr(34) + 'robotics' + chr(34) + chr(125) + ',' + chr(34) + 'Technology' + chr(34) + ':' + chr(123) + chr(34) + 'Software' + chr(34) + ':' + chr(34) + 'software OR apps' + chr(34) + ',' + chr(34) + 'Internet' + chr(34) + ':' + chr(34) + 'internet trends' + chr(34) + chr(125) + ',' + chr(34) + 'Sports' + chr(34) + ':' + chr(123) + chr(34) + 'Cricket' + chr(34) + ':' + chr(34) + 'cricket OR IPL' + chr(34) + ',' + chr(34) + 'Football' + chr(34) + ':' + chr(34) + 'football OR soccer' + chr(34) + ',' + chr(34) + 'NBA' + chr(34) + ':' + chr(34) + 'basketball OR NBA' + chr(34) + chr(125) + ',' + chr(34) + 'Business' + chr(34) + ':' + chr(123) + chr(34) + 'Startups' + chr(34) + ':' + chr(34) + 'startups' + chr(34) + ',' + chr(34) + 'Venture Capital' + chr(34) + ':' + chr(34) + 'venture capital' + chr(34) + chr(125) + ',' + chr(34) + 'Finance' + chr(34) + ':' + chr(123) + chr(34) + 'Stocks' + chr(34) + ':' + chr(34) + 'stock market' + chr(34) + ',' + chr(34) + 'Banking' + chr(34) + ':' + chr(34) + 'banking' + chr(34) + chr(125) + ',' + chr(34) + 'Health' + chr(34) + ':' + chr(123) + chr(34) + 'Medical' + chr(34) + ':' + chr(34) + 'medical research' + chr(34) + ',' + chr(34) + 'Fitness' + chr(34) + ':' + chr(34) + 'fitness' + chr(34) + chr(125) + ',' + chr(34) + 'Science' + chr(34) + ':' + chr(123) + chr(34) + 'Space' + chr(34) + ':' + chr(34) + 'NASA OR SpaceX' + chr(34) + ',' + chr(34) + 'Physics' + chr(34) + ':' + chr(34) + 'physics' + chr(34) + chr(125) + ',' + chr(34) + 'Cybersecurity' + chr(34) + ':' + chr(123) + chr(34) + 'Breaches' + chr(34) + ':' + chr(34) + 'data breach' + chr(34) + ',' + chr(34) + 'Malware' + chr(34) + ':' + chr(34) + 'malware' + chr(34) + chr(125) + ',' + chr(34) + 'Gaming' + chr(34) + ':' + chr(123) + chr(34) + 'PC/Console' + chr(34) + ':' + chr(34) + 'xbox OR playstation' + chr(34) + ',' + chr(34) + 'Mobile' + chr(34) + ':' + chr(34) + 'mobile games' + chr(34) + chr(125) + ',' + chr(34) + 'Crypto' + chr(34) + ':' + chr(123) + chr(34) + 'Bitcoin' + chr(34) + ':' + chr(34) + 'bitcoin OR ethereum' + chr(34) + ',' + chr(34) + 'Web3' + chr(34) + ':' + chr(34) + 'web3 OR NFTs' + chr(34) + chr(125) + ',' + chr(34) + 'Entertainment' + chr(34) + ':' + chr(123) + chr(34) + 'Movies' + chr(34) + ':' + chr(34) + 'movies OR netflix' + chr(34) + ',' + chr(34) + 'Music' + chr(34) + ':' + chr(34) + 'music' + chr(34) + chr(125) + ',' + chr(34) + 'World News' + chr(34) + ':' + chr(123) + chr(34) + 'Elections' + chr(34) + ':' + chr(34) + 'elections' + chr(34) + ',' + chr(34) + 'Geopolitics' + chr(34) + ':' + chr(34) + 'geopolitics' + chr(34) + chr(125) + chr(125) + ';\n'
b += 'var curD=null,days=7;\nfunction init(){\nvar sb=document.getElementById("sb");\nvar dm=document.getElementById("dm");\nvar h="";\nfor(var d in DM){h+="<div class=" + chr(34) + "sb-item" + chr(34) + " onclick=sel('" + chr(39) + d + chr(39) + "')>" + d + "</div>";\ndm.innerHTML+="<option value=" + chr(39) + d + chr(39) + ">" + d + "</option>";}\nsb.innerHTML=h;\ndm.onchange=function(){sel(this.value);\n};\nvar tk=document.getElementById("tk");\nvar tt="AI Models - IPL 2025 - Crypto Surge - SpaceX Launch - Cyber Attacks - Tesla EV - Apple WWDC - Formula 1";\ntk.innerHTML=tt.split(" - ").map(function(t){return "<span>" + t + "</span>";}).join("") + tt.split(" - ").map(function(t){return "<span>" + t + "</span>";}).join("");\nlog("info","System ready");\n}\n'
b += 'function sel(d){curD=d;document.querySelectorAll(".sb-item").forEach(function(e){e.classList.remove("active")});event.target.classList.add("active");document.getElementById("dm").value=d;var st=document.getElementById("st");var subs=Object.keys(DM[d]);st.innerHTML="";subs.forEach(function(s){st.innerHTML+="<option>" + s + "</option>";});log("ok","Domain: "+d);\n}\n'
b += 'function setD(n){days=n;document.querySelectorAll(".chip").forEach(function(c){c.classList.toggle("active",parseInt(c.dataset.d)===n);});if(curD)go();}\n'
b += 'function log(type,msg){var lg=document.getElementById("lg");var now=new Date();var t=now.getHours().toString().padStart(2,"0")+":"+now.getMinutes().toString().padStart(2,"0");var dot=type==="ok"?"dot-ok":type==="err"?"dot-err":"dot-info";lg.innerHTML="<div class=" + chr(34) + "log-entry" + chr(34) + "><span class=" + chr(34) + "log-time" + chr(34) + ">" + t + "</span><span class=" + chr(34) + "log-dot " + dot + chr(34) + "></span><span>" + msg + "</span></div>"+lg.innerHTML;}\n'
b += 'function go(){if(!curD){log("err","Select a domain");return;}var sub=document.getElementById("st").value;log("warn","Fetching "+curD+"...");document.getElementById("nc").innerHTML="<div class=" + chr(34) + "loading" + chr(34) + "><div class=" + chr(34) + "spinner" + chr(34) + "></div>Loading...</div>";fetch("/api/news?domain="+encodeURIComponent(curD)+"&subtopic="+encodeURIComponent(sub)+"&days="+days).then(function(r){return r.json();}).then(function(data){render(data);log("ok","Found "+data.length+" articles");}).catch(function(e){log("err","Error fetching");document.getElementById("nc").innerHTML="<div class=" + chr(34) + "empty" + chr(34) + "><h3>Error</h3><p>Failed to fetch news.</p></div>";});}\n'
b += 'function render(data){var groups={};data.forEach(function(a){var d=a.date_group;if(!groups[d])groups[d]=[];groups[d].push(a);});var html="";var dates=Object.keys(groups).sort().reverse();dates.forEach(function(date){var parts=date.split("-");var label=new Date(parts[0],parts[1]-1,parts[2]).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"});html+="<div class=" + chr(34) + "day-hdr" + chr(34) + "><h2>"+label+"</h2><span class=" + chr(34) + "cnt" + chr(34) + ">"+groups[date].length+" articles</span></div><div class=" + chr(34) + "grid" + chr(34) + ">";groups[date].forEach(function(a){var img=a.image_url||"";var desc=(a.content||"").substring(0,150);if(desc.length>=150)desc+="...";var src=a.author||"News";html+="<div class=" + chr(34) + "card" + chr(34) + ">";if(img)html+="<img src=" + chr(39) + img + chr(39) + " onerror=" + chr(39) + "this.style.display=" + chr(39) + chr(39) + chr(39) + " + chr(39) + ">";html+="<div class=" + chr(34) + "card-body" + chr(34) + "><div class=" + chr(34) + "card-dom" + chr(34) + ">" + curD + "</div><div class=" + chr(34) + "card-title" + chr(34) + ">" + (a.title||"") + "</div><div class=" + chr(34) + "card-desc" + chr(34) + ">" + desc + "</div><div class=" + chr(34) + "card-meta" + chr(34) + "><span>" + src + "</span><a href=" + chr(39) + (a.url||"#") + chr(39) + " target=" + chr(39) + "_blank" + chr(39) + ">Read</a></div></div></div>";});html+="</div>";});document.getElementById("nc").innerHTML=html;}\n'
b += 'function dl(){log("warn","Generating PDF...");var sub=document.getElementById("st").value;fetch("/api/generate-pdf?domain="+encodeURIComponent(curD)+"&subtopic="+encodeURIComponent(sub)+"&days="+days).then(function(r){return r.json();}).then(function(d){log("ok","PDF done! "+d.count+" articles");window.open("/api/latest-pdf","_blank");}).catch(function(e){log("err","PDF error");});}\ninit();\n</script>\n</body>\n</html>'
f=open("templates/index.html","a",encoding="utf-8")
f.write(b)
f.close()
print("CHUNK 2 DONE")
